# SPDX-License-Identifier: GPL-2.0
#rkwifi packed Makefile
# (gwl)

obj-$(CONFIG_AP6XXX) += bcmdhd/
obj-$(CONFIG_BCMDHD_101105913320) += bcmdhd_101_10_591_33_20/

.PHONY: clean

clean:
	find . -name '*.o*' -exec rm -f {} \; 
